### PR TITLE
Update client-go to v1.19.7

### PR DESCRIPTION
**Pull request by mikkeloscar**
Early spring cleaning of es-operator:

* Updates client-go to v1.19.7 (latest version running in Zalando clusters as of CW03)
* Introduces CRD generation from `types.go` file. Enhances the CRDs with better description and it will be easier to make changes in the future.

### CODE REVIEW

**Comment by mikkeloscar** [comment]
👍

**Comment by otrosien** [comment]
E2E failing: The CustomResourceDefinition "elasticsearchdatasets.zalando.org" is invalid: spec.validation.openAPIV3Schema.properties[spec].properties[scaling].properties[diskUsagePercentScaledownWatermark].type: Required value: must not be empty for specified object fields

**Comment by mikkeloscar** [comment]
@otrosien This is because we were using `float64` for the `diskUsagePercentScaledownWatermark` which is not supported by the CRD generation tooling and is generally not well supported or recommended in Kubernetes.

I have now changed the value to `int32` as I believe there is no real value in being able to define percent with float precision. All examples already use whole integers for this value.

**Comment by otrosien** [comment]
apparently something changed for mandatory attributes.

**Comment by mikkeloscar** [comment]
Correctly annotated the optional fields so they are optional in the CRD spec.

**Comment by mikkeloscar** [comment]
:+1:

**Comment by otrosien** [comment]
👍🏼

**Comment by otrosien** [comment]
👍

**Pull request merged**
