### PR TITLE
Introduce golangci-lint

### PR DESCRIPTION
**Pull request by njuettner**
## Description
Golangci-lint is a linter aggregator which enables a lot of good linters like errcheck, govet and golint.

## Types of Changes

- Travis will run golangci-lint after  running tests
- More visibility for PR's 
image

### CODE REVIEW

**Comment by otrosien** [comment]
isn't it a bit harsh to run the linting even before the tests? When I'm working on a feature I would first see the tests pass, and then do the polishing.

**Comment by njuettner** [comment]
Fixed!

**Comment by otrosien** [comment]
👍

**Comment by mikkeloscar** [comment]
:+1:

**Pull request merged**
