### PR TITLE
chore(deps): update k8s.io/* to v0.27.12

### PR DESCRIPTION
**Pull request by mikkeloscar**
This PR updates k8s.io/* to ~v0.26.14~ v0.27.12

### CODE REVIEW

**Comment by mikkeloscar** [comment]
:+1:

**Comment by otrosien** [comment]
👍

**Comment by mikkeloscar** [comment]
:+1:

**Comment by mikkeloscar** [comment]
@otrosien I fixed the failing build!

**Comment by mikkeloscar** [comment]
:+1:

**Comment by otrosien** [comment]
👍

**Pull request merged**
