### PR TITLE
VCT example fails due to not setting max_map_count

### LINKED ISSUE #108: VCT example fails due to not setting max_map_count
## Expected Behavior
Running https://github.com/zalando-incubator/es-operator/blob/master/docs/elasticsearchdataset-vct.yaml should result in a working cluster.

## Actual Behavior
Running https://github.com/zalando-incubator/es-operator/blob/master/docs/elasticsearchdataset-vct.yaml fails with a crash loop back off, with a boot time check failure.

## Steps to Reproduce the Problem

  1. Run https://github.com/zalando-incubator/es-operator/blob/master/docs/elasticsearchdataset-vct.yaml after creating a master

## Specifications

  - Version:
  - Platform:
  - Subsystem:

The initContainer that sets vm.max_map_count is missing in the VCT example.

### PR DESCRIPTION
**Pull request by otrosien**
Change: Added init container to raise max_map_count.

Closes #108

### CODE REVIEW

**Comment by otrosien** [comment]
👍

**Comment by mikkeloscar** [comment]
@otrosien DCO missing

**Comment by otrosien** [comment]
👍

**Comment by mikkeloscar** [comment]
:+1:

**Pull request merged**
