### PR TITLE
Update to Kubernetes v1.30.2

### PR DESCRIPTION
**Pull request by mikkeloscar**
Update dependencies to Kubernetes v1.30.2

### CODE REVIEW

**Comment by otrosien** [comment]
@mikkeloscar you have been doing all the kubernetes upgrades so far. Is there some template or documentation you're following for this? (in order to spread some knowledge among the maintainers..)

**Comment by linki** [comment]
👍

**Comment by otrosien** [comment]
👍

**Comment by mikkeloscar** [comment]
@otrosien This update was particularly non-trivial because the code gen tools were updated and the flags etc. changed, so I went through what changed and adjusted it.

Normally it's just about updating the version in go.mod. Here is a simple script to simplify it:

```sh
#!/usr/bin/env bash

set -euo pipefail

package_path="${1:-"."}"
k8s_version="v0.30.2"
go_version="1.22"

cd "$package_path" || exit

sed -i "s/^\(\s\+k8s.io\/.*\)\sv0\.[[:digit:]]\+\.[[:digit:]]\+$/\1 ${k8s_version}/g" go.mod
sed -i "s/^go 1\.[[:digit:]]\+$/go ${go_version}/g" go.mod

for p in $(go mod edit -json | jq -r '.Require[] | select(.Indirect != true) | .Path' | grep -v "k8s.io"); do
    go get -u "$p"
done

go mod tidy


# verify build
make clean
make
make test
```

**Pull request merged**
